export const IMAGES = {
  avantGardeFashion: "/images/avant-garde-fashion.jpg",
  chromeVisorPortrait: "/images/chrome-visor-portrait.jpg",
  wetSkinPortrait: "/images/wet-skin-portrait.jpg",
  silverVisorPortrait: "/images/silver-visor-portrait.jpg",
  editorialReach: "/images/editorial-reach.jpg",
  chunkyBootsFashion: "/images/chunky-boots-fashion.jpg",
  baggyDenimFashion: "/images/baggy-denim-fashion.jpg",
  skateboardDollarGraphic: "/images/skateboard-dollar-graphic.jpg",
  jacksonYeeWide: "/images/jackson-yee-wide.jpg",
  mahmoodWarmPortrait: "/images/mahmood-warm-portrait.jpg",
  baggyJeansStrut: "/images/baggy-jeans-strut.jpg",
  greyFleecePose: "/images/grey-fleece-pose.jpg",
  blackJacketShades: "/images/black-jacket-shades.jpg",
  sunsetSilhouetteCollage: "/images/sunset-silhouette-collage.jpg",
  fisheyePufferVest: "/images/fisheye-puffer-vest.jpg",
  wideAngleHeadphones: "/images/wide-angle-headphones.jpg",
  footer: [
    "/images/footer1.webp",
    "/images/footer2.webp",
    "/images/footer3.webp",
    "/images/footer4.webp",
    "/images/footer5.webp",
    "/images/footer6.webp",
  ],
} as const;
