import { ExtendedTrackItem } from "./types";

export const DEFAULT_TRACKS: ExtendedTrackItem[] = [
  {
    id: "t1",
    title: "Horizon",
    artist: "C418",
    album: "MINECRAFT",
    duration: "04:12",
    year: "2025",
    imageSrc: "/images/components/tracklist-gallery/aria-math.webp",
    audioSrc: "/audio/components/tracklist-gallery/aria-math.mp3",
    accentBg: "#172314",
    titleColor: "#DCE8CD",
    audioStartTime: 13.5,
  },
  {
    id: "t2",
    title: "Sunken Echo",
    artist: "TITE KUBO",
    album: "BLEACH",
    duration: "03:48",
    year: "2024",
    imageSrc: "/images/components/tracklist-gallery/clavar-la-espada.webp",
    audioSrc: "/audio/components/tracklist-gallery/clavar-la-espada.mp3",
    accentBg: "#2C1411",
    titleColor: "#F4C9BE",
  },
  {
    id: "t3",
    title: "Afterglow",
    artist: "DORIAN CONCEPT",
    album: "HIDE CS01",
    duration: "05:04",
    year: "2025",
    imageSrc: "/images/components/tracklist-gallery/hide.webp",
    audioSrc: "/audio/components/tracklist-gallery/hide.mp3",
    accentBg: "#0E1E28",
    titleColor: "#BFE6FA",
  },
  {
    id: "t4",
    title: "Paper Cranes",
    artist: "GIBRAN ALCOCER",
    album: "IDEA 10",
    duration: "04:30",
    year: "2024",
    imageSrc: "/images/components/tracklist-gallery/idea-10.webp",
    audioSrc: "/audio/components/tracklist-gallery/idea-10.mp3",
    accentBg: "#1C1E24",
    titleColor: "#E5E7EB",
  },
  {
    id: "t5",
    title: "Dust & Gold",
    artist: "HANS ZIMMER",
    album: "INTERSTELLAR",
    duration: "06:15",
    year: "2025",
    imageSrc: "/images/components/tracklist-gallery/cornfield-chase.webp",
    audioSrc: "/audio/components/tracklist-gallery/cornfield-chase.mp3",
    accentBg: "#251B12",
    titleColor: "#FCE8C9",
    audioStartTime: 4.0,
  },
  {
    id: "t6",
    title: "Solitude",
    artist: "JAMIE DUFFY",
    album: "SOLAS",
    duration: "03:55",
    year: "2024",
    imageSrc: "/images/components/tracklist-gallery/solas.webp",
    audioSrc: "/audio/components/tracklist-gallery/solas.mp3",
    accentBg: "#1F1713",
    titleColor: "#EBD3BF",
  },
  {
    id: "t7",
    title: "Before The Rain",
    artist: "LUDOVICO EINAUDI",
    album: "EXPERIENCE",
    duration: "04:45",
    year: "2025",
    imageSrc: "/images/components/tracklist-gallery/experience.webp",
    audioSrc: "/audio/components/tracklist-gallery/experience.mp3",
    accentBg: "#0F2218",
    titleColor: "#C3E8D2",
    audioStartTime: 3.5,
  },
  {
    id: "t8",
    title: "Nocturne",
    artist: "STRUCT",
    album: "SLOWED",
    duration: "05:22",
    year: "2024",
    imageSrc: "/images/components/tracklist-gallery/struct.webp",
    audioSrc: "/audio/components/tracklist-gallery/struct.mp3",
    accentBg: "#111217",
    titleColor: "#DCE4F5",
  },
];
